# Generated by Django 5.2.4 on 2026-07-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_article_published_article_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(max_length=1,choices=[('p', 'publish'), ('d', 'draft')], default='d'),
        ),
    ]
